name: Build LaTeX document
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          latexmk_use_xelatex: true
          root_file: NickStocktonResume.tex
      - name: Copy Artifact to public folder
        run: cp NickStocktonResume.pdf public/
      - name: Upload to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
